version: '3.9'

services:
  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - upload_service
      - download_service
      - minio
    volumes:
      - ./etc/nginx:/etc/nginx

  db:
    image: mongo:5.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    env_file:
      - mongodb.env

  minio:
    image: bitnami/minio:latest
    restart: on-failure
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - minio.env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 10s
      timeout: 20s
      retries: 5

  upload_service:
    image: ghcr.io/opnsnap/upload-service:main
    restart: on-failure
    expose:
      - 8080
    env_file:
      - minio.env
    depends_on:
      minio:
        condition: service_healthy

  download_service:
    image: ghcr.io/opnsnap/download-service:main
    restart: on-failure
    expose:
      - 8080
    env_file:
      - minio.env
    depends_on:
      minio:
        condition: service_healthy
volumes:
  db: {}
